const { buildSync } = require("esbuild");
const { readFileSync } = require("node:fs");

const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
const pkg = JSON.parse(readFileSync("package.json", "utf8"));
if (manifest.version !== pkg.version) throw new Error("Version mismatch");

const licenses = [
  ["markdown-it", "LICENSE"],
  ["entities", "LICENSE"],
  ["linkify-it", "LICENSE"],
  ["mdurl", "LICENSE"],
  ["punycode.js", "LICENSE-MIT.txt"],
  ["uc.micro", "LICENSE.txt"]
].map(([name, file]) => `${name}\n${readFileSync(`node_modules/${name}/${file}`, "utf8")}`).join("\n\n");

buildSync({
  entryPoints: ["src/main.js"],
  outfile: "main.js",
  bundle: true,
  platform: "browser",
  format: "cjs",
  target: "es2020",
  external: ["obsidian", "@codemirror/state", "@codemirror/view", "@codemirror/language"],
  minify: true,
  legalComments: "eof",
  banner: { js: "// Generated by npm run build. Edit src/ instead." },
  footer: { js: `/* Bundled dependency licenses\n${licenses.replace(/\*\//g, "* /")}\n*/` }
});
